version: '3.3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8001:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/swagger.json
  web:
    build: .
    restart: on-failure:3
    command: ./server
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - .:/app
    networks:
      custom_network:


networks:
  custom_network:
    driver: bridge